id: I9ACBCEDC
default_language: bo
source: https://www2.hf.uio.no/polyglotta/index.php?page=library&bid=2
initial_creation_type: input
imported: 2023-02-10 00:12:48.061908
last_modified: 2023-02-10 00:12:48.062244
source_metadata:
  title: 'MSV 6,01: Upāliparipṛcchā'
  language: bo
bases:
  '6914':
    base_file: 6914.txt
    order: 1
copyright:
  status: Unknown
  notice: ''
